openapi: 3.0.0
info:
  title: Pet project
  version: 1.0.0
servers:
- url: http://localhost:30000
paths:
  /token:
    post:
      tags:
      - authentication
      summary: Returns authorization token
      operationId: tokenPOST
      requestBody:
        description: oauth2 standard body
        content:
          'application/x-www-form-urlencoded:':
            schema:
              $ref: '#/components/schemas/body'
            examples:
              password:
                summary: Get token by password
                value:
                  grant_type: password
                  client_id: MyClientId
                  username: MyUsername
                  password: MyPassword
              client_credentials:
                summary: Get token by client credentials
                value:
                  grant_type: client_credentials
                  client_id: MyClientId
                  client_secret: MyClientSecret
              refresh_token:
                summary: Get token by refresh
                value:
                  grant_type: refresh_token
                  client_id: MyClientId
                  client_secret: MyClientSecret
                  refresh_token: MyRefreshToken
        required: true
      responses:
        "200":
          description: Access token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: body
      x-swagger-router-controller: Authentication
  /user:
    get:
      tags:
      - user
      summary: 'Sample endpoint: Returns details about a particular user'
      operationId: listUser
      parameters:
      - name: id
        in: query
        description: ID of the user
        required: true
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: User
components:
  securitySchemes:
    oAuthSample:    # <---- arbitrary name
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        clientCredentials:   # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
          tokenUrl: /token
  schemas:
    Oauth2_password:
      required:
      - client_id
      - grant_type
      - password
      - username
      type: object
      properties:
        grant_type:
          type: string
          description: Type of authentication used
          example: password
          default: password
          enum:
          - password
        client_id:
          type: string
          description: Id of the authorization client
          example: MyClientId
        password:
          type: string
          description: password used to authenticate
          example: MyPassword
        username:
          type: string
          description: username used to authenticate
          example: MyUsername
    Oauth2_client_credentials:
      required:
      - client_id
      - client_secret
      - grant_type
      type: object
      properties:
        grant_type:
          type: string
          description: Type of authentication used
          default: client_credentials
          enum:
          - client_credentials
        client_id:
          type: string
          example: MyclientId
        client_secret:
          type: string
          example: MySecret
    Oauth2_refresh_token:
      required:
      - client_id
      - client_secret
      - grant_type
      - refresh_token
      type: object
      properties:
        grant_type:
          type: string
          description: Type of authentication used
          default: refresh_token
          enum:
          - refresh_token
        client_id:
          type: string
          example: MyClient
        client_secret:
          type: string
          example: MySecret
        refresh_token:
          type: string
          example: MyToken
    Token:
      type: object
      properties:
        access_token:
          type: string
          example: Thisisatoken
        token_type:
          type: string
          example: bearer
        expires_in:
          type: string
          example: "1560"
        refresh_token:
          type: string
          example: this is a refreshtoken
        scope:
          type: string
          example: '*'
      example:
        access_token: Thisisatoken
        refresh_token: this is a refreshtoken
        scope: '*'
        token_type: bearer
        expires_in: "1560"
    User:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
      example:
        name: name
        id: 0
        tag: tag
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    
    body:
      discriminator:
        propertyName: grant_type
      oneOf:
      - $ref: '#/components/schemas/Oauth2_password'
      - $ref: '#/components/schemas/Oauth2_client_credentials'
      - $ref: '#/components/schemas/Oauth2_refresh_token'
      
security: 
  - oAuthSample: 
    - read_User